version: '3'

services:
  django_backend:
    container_name: django-backend
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    restart: on-failure