version: '3'

services:
    api:
      build: .
      ports:
        - "8000:8000"
      volumes:
        - .:/code
      environment:
        - SECRET_KEY=${SECRET_KEY}
        - DEBUG=${DEBUG}
      