# Generated by Django 5.0.3 on 2024-03-22 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_alter_note_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='content',
            new_name='description',
        ),
    ]
