# Generated by Django 5.0.3 on 2024-03-24 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_rename_content_note_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-created_at']},
        ),
    ]
